### ISSUE TITLE
Clicking update button causes error

### ISSUE THREAD

**Issue by saas786** [Dziemborowicz/Hourglass#119]
Hi,

Whenever I create new timer, enter title, enter time and then click "update" it throws error.

**Comment by Dziemborowicz** [comment]
Can you provide some more details? There should be a "Show details" button in the error dialog, switch should show more information.

**Comment by saas786** [comment]
See attachment.

[Hourglass-Crash.20160823-150806-6997761.txt](https://github.com/Dziemborowicz/Hourglass/files/432238/Hourglass-Crash.20160823-150806-6997761.txt)

**Comment by Dziemborowicz** [comment]
Looks like you might not have a default web browser set... That shouldn't crash the app, of course, though.

Clicking the "Update" button just opens http://chris.dziemborowicz.com/apps/hourglass/ in the default web browser, so that you can download the latest installer. It's not very sophisticated at the moment.

Downloading the latest version from http://chris.dziemborowicz.com/apps/hourglass/ should resolve this problem for now, and I'll fix this crash when I have a minute.

**Comment by saas786** [comment]
I see. 

Hopefully you will fix it ASAP :)

As I don't like to recreate timers again and again which I use frequently.

I would like the ability to save timers and re-use them later on when needed.

**Comment by Dziemborowicz** [comment]
If there is no default browser set, the "Update" button now directs the user to visit the web site to download the latest version.
