### ISSUE TITLE
Why does Hourglass require Internet Explorer to be installed?

### ISSUE THREAD

**Issue by mindstormer12** [Dziemborowicz/Hourglass#84]
I read through the details on the Hourglass page and am wondering why Hourglass requires Internet Explorer to be installed.

 Also, is there a possibility to make the program truly portable by removing the requirement of Microsoft .NET Framework 4.0 Client Profile?

Lastly, what are the advantages of installing Hourglass over using the portable version? All I know is that installed programs typically create registries to store settings while portable versions tend to save all their settings in a text file--not sure if this is the only difference between the two versions and if registries are somehow preferable to text files.

Otherwise, great job on the application.

**Comment by Dziemborowicz** [comment]
1) Hourglass does not have any system requirements above and beyond what is required for Microsoft .NET Framework 4.0 Client Profile.

Internet Explorer is listed as a system requirement for Hourglass only because Microsoft lists it as a system requirement for Microsoft .NET Framework 4.0 Client Profile.

2) The Hourglass user interface uses Windows Presentation Foundation, and all of the code is written in C#. Removing the Microsoft .NET Framework 4.0 Client Profile would require rewriting the application in native code. I don't currently have plans to do that -- it would be quite a bit of work.

3) Installing Hourglass places a shortcut in your Start Menu, puts Hourglass.exe somewhere sensible (typically "C:\Program Files (x86)"), and stores your settings under in your user profile (typically "C:\Users\<user>\AppData\Local").

If you use the portable version, you have to put Hourglass.exe somewhere sensible yourself, and launch the app by double-clicking the Hourglass.exe or manually create a shortcut somewhere. With the portable version, settings are stored in a file that lives next to the .exe file.
